### ISSUE TITLE
Add support for paths

### ISSUE THREAD

**Issue by daprahamian** [bendrucker/globo#3]
This is a followup to [this issue on browserify-shim](https://github.com/thlorenz/browserify-shim/issues/180). Prior to 1.0.1, you could execute items like `globo('Backbone.Marionette');`, and get a working path back to `window.Backbone.Marionette`. Now, however, it becomes `window["Backbone.Marionette"];`

**Comment by bendrucker** [comment]
Almost got this ready to push

**Comment by bendrucker** [comment]
Shipped in d6707d81829213afc004dd7d77e28a90db7e9596. Dots are treated as paths, unless you escape them with a backslash. But instead of just appending, the result is `window['Backbone']['Marionette']` to keep things simple.
